setwd("C:/Users/Administrator/Downloads")
getwd()
data1 = read.csv("Q9_b.csv")
skewness(data1$SP)
kurtosis(data1$SP)
skewness(data1$WT)
kurtosis(data1$WT)
plot(data1$WT, data1$SP, xlab = "WT", ylab = "SP", type = 'p', col = "blue",pch = 19)
boxplot(data1$SP, col = 'darkred')
summary(data1)
